
import React, { useState } from 'react';
import { Code, Eye, Download, Copy, Play, Check, Terminal, Package } from 'lucide-react';
import { buildWebsite } from '../services/aiService';

// Declare JSZip from global script
declare const JSZip: any;

const WebBuilderView: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [view, setView] = useState<'editor' | 'preview'>('editor');
  const [copied, setCopied] = useState(false);
  const isAr = document.documentElement.lang === 'ar';

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    
    // Call the Orchestrated Builder
    const res = await buildWebsite(prompt);
    
    // Basic cleaning of markdown markers
    const cleaned = res.replace(/```(html|jsx|tsx|javascript|css)?/g, '').replace(/```/g, '').trim();
    setCode(cleaned);
    setLoading(false);
    setView('preview');
  };

  const handleDownloadZip = async () => {
    if (!code || !JSZip) return;
    
    const zip = new JSZip();
    // Add index.html
    zip.file("index.html", code);
    // Add README
    zip.file("README.txt", `Website generated by Teacher AI (Web Builder Mode).\n\nPrompt: ${prompt}\nDate: ${new Date().toLocaleString()}`);
    
    // Generate and trigger download
    const content = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(content);
    const link = document.createElement('a');
    link.href = url;
    link.download = "teacher_ai_website.zip";
    link.click();
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-20">
      <div className="bg-[#111827]/60 border border-white/10 rounded-3xl p-6 md:p-8 shadow-2xl backdrop-blur-xl">
        <div className="flex flex-col gap-4">
          <label className={`text-blue-400 font-black uppercase tracking-widest text-xs flex items-center gap-2 ${isAr ? 'flex-row-reverse' : ''}`}>
            <Terminal className="w-4 h-4" />
            {isAr ? 'وصف المشروع' : 'Project Prompt'}
          </label>
          <div className={`flex flex-col md:flex-row gap-3 ${isAr ? 'flex-row-reverse' : ''}`}>
            <input
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={isAr ? "مثال: موقع إخباري تقني مع الوضع الليلي..." : "e.g. A tech news website with dark mode..."}
              className={`flex-1 bg-black/40 border border-white/10 rounded-2xl py-4 px-6 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all text-sm md:text-base text-white placeholder:text-slate-600 ${isAr ? 'text-right' : 'text-left'}`}
              dir={isAr ? 'rtl' : 'ltr'}
            />
            <button
              onClick={handleGenerate}
              disabled={loading || !prompt.trim()}
              className="px-8 py-4 bg-blue-600 hover:bg-blue-500 text-white font-black rounded-2xl flex items-center justify-center gap-2 transition-all disabled:opacity-50 shadow-xl shadow-blue-600/20 active:scale-95 uppercase tracking-wider text-xs md:text-sm"
            >
              {loading ? <Terminal className="w-5 h-5 animate-pulse" /> : <Play className="w-5 h-5" />}
              {isAr ? 'بناء الموقع' : 'Build Site'}
            </button>
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-6 min-h-[50vh] md:min-h-[600px]">
        <div className="w-full flex flex-col gap-4">
          <div className={`flex items-center justify-between bg-[#111827]/80 p-2 rounded-2xl border border-white/10 backdrop-blur-md ${isAr ? 'flex-row-reverse' : ''}`}>
            <div className="flex gap-1">
              <button 
                onClick={() => setView('editor')}
                className={`px-4 md:px-6 py-2.5 rounded-xl text-[10px] md:text-xs font-black uppercase tracking-wider flex items-center gap-2 transition-all ${view === 'editor' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
              >
                <Code className="w-4 h-4" /> {isAr ? 'الكود' : 'Code'}
              </button>
              <button 
                onClick={() => setView('preview')}
                className={`px-4 md:px-6 py-2.5 rounded-xl text-[10px] md:text-xs font-black uppercase tracking-wider flex items-center gap-2 transition-all ${view === 'preview' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
              >
                <Eye className="w-4 h-4" /> {isAr ? 'المعاينة' : 'Preview'}
              </button>
            </div>
            <div className={`flex gap-2 ${isAr ? 'mr-0 ml-2' : 'mr-2'}`}>
              <button 
                onClick={() => {
                  navigator.clipboard.writeText(code);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                }}
                className="p-2.5 bg-white/5 hover:bg-white/10 rounded-xl transition-all text-slate-400 hover:text-white border border-white/5"
                title="Copy Code"
              >
                {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              </button>
              <button 
                onClick={handleDownloadZip}
                disabled={!code}
                className="p-2.5 bg-white/5 hover:bg-blue-600 rounded-xl transition-all text-slate-400 hover:text-white border border-white/5 disabled:opacity-30 disabled:hover:bg-white/5"
                title="Download ZIP"
              >
                <Package className="w-4 h-4" />
              </button>
            </div>
          </div>

          <div className="flex-1 bg-[#050505] border border-white/10 rounded-3xl overflow-hidden relative shadow-2xl h-[50vh] md:h-[600px]">
            {loading && (
              <div className="absolute inset-0 flex items-center justify-center bg-black/80 backdrop-blur-sm z-20">
                <div className="text-center space-y-4">
                  <div className="relative w-20 h-20 mx-auto">
                    <div className="absolute inset-0 border-4 border-blue-500/20 rounded-full"></div>
                    <div className="absolute inset-0 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
                    <Terminal className="absolute inset-0 m-auto w-8 h-8 text-blue-400 animate-pulse" />
                  </div>
                  <div className="space-y-1">
                    <p className="text-blue-400 font-black uppercase tracking-[0.2em] animate-pulse">{isAr ? 'البناء العصبي' : 'Neural Construction'}</p>
                    <p className="text-[10px] text-slate-500 font-mono">{isAr ? 'Puter Architect → SerpAPI → Qroq Builder' : 'Puter Architect → SerpAPI → Qroq Builder'}</p>
                  </div>
                </div>
              </div>
            )}
            
            {view === 'editor' ? (
              <pre className={`p-6 text-sm font-mono text-blue-300 overflow-auto h-full scrollbar-thin bg-[#0a0a0c] ${isAr ? 'text-left' : 'text-left'}`} dir="ltr">
                {code || (isAr ? '// النظام بانتظار تعليمات البناء...' : '// System waiting for build instructions...')}
              </pre>
            ) : (
              <iframe
                title="Preview"
                className="w-full h-full bg-white"
                srcDoc={code || `
                  <!DOCTYPE html>
                  <html>
                    <head>
                      <script src="https://cdn.tailwindcss.com"></script>
                    </head>
                    <body class="bg-gray-100 h-screen flex flex-col items-center justify-center text-gray-400 gap-4">
                      <svg class="w-16 h-16 opacity-20" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path></svg>
                      <p class="font-mono text-sm">${isAr ? 'منطقة المعاينة' : 'Preview Area'}</p>
                    </body>
                  </html>
                `}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default WebBuilderView;
